In [1]:
import pandas as pd

In [2]:
model_order = [
    "OpenAI/o1-preview-2024-09-12",
    "deepseek-ai/DeepSeek-R1",
    "Google/gemini-15-Pro-002",
    "OpenAI/gpt-4o-2024-08-06",
    "deepseek-ai/DeepSeek-V3-0324",
    "meta-llama/Llama-3.1-405B",
    "Anthropic/claude-3-5-sonnet-20241022",
    "Qwen/Qwen2.5-32B",
    "microsoft/phi-4",
    "mistralai/Pixtral-12B-2409",
    "CohereLabs/aya-23-35B"
]

In [3]:
df = pd.read_csv('full/accuracy_by_subject_language.csv')
# # Drop o1-preview column
# df = df.drop(columns=['OpenAI/o1-preview-2024-09-12'])
df.head()

,subject,language,Anthropic/claude-3-5-sonnet-20241022,CohereLabs/aya-23-35B,Google/gemini-15-Pro-002,OpenAI/gpt-4o-2024-08-06,OpenAI/o1-preview-2024-09-12,Qwen/Qwen2.5-32B,deepseek-ai/DeepSeek-R1,deepseek-ai/DeepSeek-V3-0324,meta-llama/Llama-3.1-405B,microsoft/phi-4,mistralai/Pixtral-12B-2409
0,elementary_mathematics,amh,0.61,0.23,0.81,0.82,0.79,0.53,0.94,0.83,0.73,0.47,0.38
1,elementary_mathematics,eng,0.63,0.42,0.93,0.95,0.99,0.78,1.00,0.96,0.85,0.66,0.41
2,elementary_mathematics,ewe,0.47,0.27,0.71,0.64,0.61,0.51,0.72,0.66,0.58,0.37,0.38
3,elementary_mathematics,fra,0.70,0.35,0.86,0.88,0.93,0.70,0.96,0.89,0.82,0.65,0.37
4,elementary_mathematics,hau,0.58,0.28,0.82,0.83,0.92,0.52,0.95,0.76,0.66,0.43,0.34

In [4]:
df = pd.read_csv('full/accuracy_by_subject_language.csv')
# # Drop o1-preview column
# df = df.drop(columns=['OpenAI/o1-preview-2024-09-12'])
# Drop any rows with language 'fra' and 'eng'
df = df[df['language'] != 'eng']
df = df[df['language'] != 'fra']
# Drop the 'language' column before grouping
df = df.drop(columns=['language'])
# Group by subject and average across all languages
df = df.groupby('subject').mean().reset_index()
# Swap rows and columns
df = df.set_index('subject').T
# Rename the index to 'model'
df.index.name = 'model'
# Rename the columns to 'subject'
df.columns.name = 'subject'
# Add a new column 'total' that is the average of all columns
df['total'] = df.mean(axis=1)
# Reorder the columns to have 'total' at the end
df = df[['total'] + [col for col in df.columns if col != 'total']]
# round the values to 3 decimal places
df = df.round(3)
# multiply by 100
df = df * 100
# Reorder rows to match the model_order
df = df.reindex(model_order)
# Change row names to be more readable (keep only everything after the last '/')
df.index = df.index.str.split('/').str[-1]
df

subject,total,elementary_mathematics,global_facts,high_school_geography,high_school_microeconomics,international_law
model,,,,,,
o1-preview-2024-09-12,75.6,88.2,67.2,71.8,75.4,75.7
DeepSeek-R1,67.1,87.8,56.1,60.2,63.2,68.1
gemini-15-Pro-002,62.3,78.0,54.6,56.1,54.5,68.1
gpt-4o-2024-08-06,62.2,79.6,47.6,58.1,58.4,67.4
DeepSeek-V3-0324,54.0,76.2,48.6,46.6,44.6,53.8
Llama-3.1-405B,51.1,68.9,44.6,42.1,40.5,59.4
claude-3-5-sonnet-20241022,49.6,59.0,46.4,48.4,42.5,51.5
Qwen2.5-32B,39.0,52.9,33.5,27.1,31.3,50.2
phi-4,37.0,43.8,35.8,28.6,28.7,47.9
Pixtral-12B-2409,33.0,34.7,30.9,30.4,30.6,38.6
aya-23-35B,23.5,25.8,19.9,19.1,24.2,28.4

In [5]:
df = pd.read_csv('full/accuracy_by_subject_language.csv')
# # Drop o1-preview column
# df = df.drop(columns=['OpenAI/o1-preview-2024-09-12'])
# Keep only rows with language 'eng'
df = df[df['language'] == 'eng']
# Drop the 'language' column before grouping
df = df.drop(columns=['language'])
# Group by subject and average across all languages
df = df.groupby('subject').mean().reset_index()
# Swap rows and columns
df = df.set_index('subject').T
# Rename the index to 'model'
df.index.name = 'model'
# Rename the columns to 'subject'
df.columns.name = 'subject'
# Add a new column 'total' that is the average of all columns
df['total'] = df.mean(axis=1)
# Reorder the columns to have 'total' at the end
df = df[['total'] + [col for col in df.columns if col != 'total']]
# round the values to 3 decimal places
df = df.round(3)
# multiply by 100
df = df * 100
# Reorder rows to match the model_order
df = df.reindex(model_order)
# Change row names to be more readable (keep only everything after the last '/')
df.index = df.index.str.split('/').str[-1]
df

subject,total,elementary_mathematics,global_facts,high_school_geography,high_school_microeconomics,international_law
model,,,,,,
o1-preview-2024-09-12,90.6,99.0,75.0,91.0,97.0,91.0
DeepSeek-R1,90.0,100.0,65.0,95.0,99.0,91.0
gemini-15-Pro-002,88.2,93.0,69.0,91.0,96.0,92.0
gpt-4o-2024-08-06,88.6,95.0,68.0,92.0,97.0,91.0
DeepSeek-V3-0324,88.4,96.0,67.0,92.0,98.0,89.0
Llama-3.1-405B,85.8,85.0,66.0,92.0,97.0,89.0
claude-3-5-sonnet-20241022,75.0,63.0,66.0,87.0,81.0,78.0
Qwen2.5-32B,79.2,78.0,55.0,86.0,88.0,89.0
phi-4,77.4,66.0,45.0,92.0,95.0,89.0
Pixtral-12B-2409,62.2,41.0,43.0,78.0,73.0,76.0
aya-23-35B,57.4,42.0,43.0,67.0,69.0,66.0

In [6]:
df = pd.read_csv('full/accuracy_by_subject_language.csv')
# # Drop o1-preview column
# df = df.drop(columns=['OpenAI/o1-preview-2024-09-12'])
# Keep only rows with language 'fra'
df = df[df['language'] == 'fra']
# Drop the 'language' column before grouping
df = df.drop(columns=['language'])
# Group by subject and average across all languages
df = df.groupby('subject').mean().reset_index()
# Swap rows and columns
df = df.set_index('subject').T
# Rename the index to 'model'
df.index.name = 'model'
# Rename the columns to 'subject'
df.columns.name = 'subject'
# Add a new column 'total' that is the average of all columns
df['total'] = df.mean(axis=1)
# Reorder the columns to have 'total' at the end
df = df[['total'] + [col for col in df.columns if col != 'total']]
# round the values to 3 decimal places
df = df.round(3)
# multiply by 100
df = df * 100
# Reorder rows to match the model_order
df = df.reindex(model_order)
# Change row names to be more readable (keep only everything after the last '/')
df.index = df.index.str.split('/').str[-1]
df

subject,total,elementary_mathematics,global_facts,high_school_geography,high_school_microeconomics,international_law
model,,,,,,
o1-preview-2024-09-12,88.8,93.0,75.0,90.0,95.0,91.0
DeepSeek-R1,87.4,96.0,68.0,85.0,97.0,91.0
gemini-15-Pro-002,85.0,86.0,65.0,89.0,94.0,91.0
gpt-4o-2024-08-06,83.0,88.0,60.0,86.0,90.0,91.0
DeepSeek-V3-0324,83.2,89.0,63.0,86.0,90.0,88.0
Llama-3.1-405B,80.8,82.0,63.0,85.0,90.0,84.0
claude-3-5-sonnet-20241022,71.2,70.0,53.0,87.0,80.0,66.0
Qwen2.5-32B,72.8,70.0,54.0,78.0,80.0,82.0
phi-4,72.6,65.0,47.0,83.0,82.0,86.0
Pixtral-12B-2409,54.6,37.0,41.0,66.0,58.0,71.0
aya-23-35B,43.6,35.0,26.0,41.0,51.0,65.0

In [7]:
model_df = pd.read_csv('../../model_df.csv')
# Drop 'OpenAI_o1'
model_df = model_df[model_df['dir'] != 'OpenAI_o1']
sums = []
for dir in model_df['dir']:
    # Read the CSV file
    df = pd.read_csv(f'full/{dir}_full_results.csv')
    # Sum the 'num_tokens' column
    sum = df['num_tokens'].sum()
    # Append the sum to the list
    sums.append(sum)
# Add the sums as a new column to the model_df DataFrame
model_df['num_tokens'] = sums
# Drop all columns except 'dir', 'tokenizer', and 'num_tokens'
model_df = model_df[['dir', 'tokenizer', 'num_tokens']]
# Add an avg row
avg_row = pd.DataFrame({'dir': ['Avg'], 'num_tokens': [model_df['num_tokens'].mean()]})
# Add a total row (without the avg)
total_row = pd.DataFrame({'dir': ['Total'], 'num_tokens': [model_df['num_tokens'].sum()]})
# Append the avg and total rows to the model_df DataFrame
model_df = pd.concat([model_df, avg_row], ignore_index=True)
model_df = pd.concat([model_df, total_row], ignore_index=True)
# Rename the 'dir' column to 'Model'
model_df = model_df.rename(columns={'dir': 'Model'})
# Set the display option to show num_tokens as int
pd.set_option('display.float_format', '{:.0f}'.format)

model_df

                    Model                     tokenizer  num_tokens
0      Anthropic_Sonnet35   anthropic/claude-3.5-sonnet     1159265
1   CohereForAI_Aya23_35B         CohereLabs/aya-23-35B     1018523
2             DeepSeek_R1       deepseek-ai/DeepSeek-R1     1032339
3             DeepSeek_V3  deepseek-ai/DeepSeek-V3-0324     1032339
4         Gemini15_Pro002     google/gemini-1.5-pro-002      915028
5            Llama31_405B     meta-llama/Llama-3.1-405B     1085020
6          Microsoft_Phi4               microsoft/phi-4     1103368
7            OpenAI_GPT4o      openai/gpt-4o/o200k_base      876352
8        Pixtral_12B_2409    mistralai/Pixtral-12B-2409     1112784
9              Qwen25_32B              Qwen/Qwen2.5-32B     1017587
10                    Avg                           NaN     1035260
11                  Total                           NaN    10352605